#!/bin/bash
#
# Gets and prints an amdgpu-supported card's current utilization and associated
# state (low or high utilization).

# replace hwmon# by actual card's hwmon number
usage=$(</sys/class/drm/card*/device/gpu_busy_percent)

# bad, yes, but there is no native way to use ordered arrays
# some of these clauses are for padding the output
if [[ ${usage} -ge 90 ]]; then
  printf '%s\n\nvery-high\n' "${usage}"
elif [[ ${usage} -ge 75 ]]; then
  printf '%s\n\nhigh\n' "${usage}"
elif [[ ${usage} -ge 50 ]]; then
  printf '%s\n\nmedium\n' "${usage}"
elif [[ ${usage} -ge 25 ]]; then
  printf '%s\n\nlow\n' "${usage}"
elif [[ ${usage} -ge 5 ]]; then
  printf '%s\n\nvery-low\n' "${usage}"
else
  printf '%s\n\n\n' "${usage}"
fi
