#!/bin/bash
#
# Quickly change the Rosé Pine theme variant across many personal apps.

set -x

########################################
# Change theme for multiple apps using symbolic linking hacks or sed editing
# in-place.
# Arguments:
#   name: blank, '-dawn' or '-moon'
#     NOTE: Pay attention to the hyphens in ${name} for light theme!
#   pretty_name: 'main', 'dawn' or 'moon'
#   mode: 'dark', or 'light'
# Returns:
#   0 if all themes were succesfully changed (even if the same theme was already
#   set).
#   Non-zero on error.
########################################
function change_theme() {
  # File
  printf 'rose-pine-%s\n' "${pretty_name}" >"$XDG_CONFIG_HOME"/theme

  # GTK
  gsettings set org.gnome.desktop.interface gtk-theme "rose-pine${name}-gtk"
  gsettings set org.gnome.desktop.interface color-scheme "prefer-${mode}"

  # TODO: Qt

  # Not present on my Termux.
  # shellcheck disable=2164
  cd "${HOME}"/.mozilla/firefox/dq6prhb9.arkenfox
  ln -sf "userChrome-${pretty_name}.css" chrome/rose-pine/dist/userChrome.css
  ln -sf "userColors-${pretty_name}.css" chrome/rose-pine/dist/userColors.css

  cd "${XDG_CONFIG_HOME}"/alacritty || exit
  # sed -i "s/rose-pine.*\.toml/rose-pine${name}\.toml/" alacritty.toml
  sed -i "s/rose-pine.*\.toml/rose-pine${name}\.toml/" alacritty.toml
  if [[ "${pretty_name}" == "main" || "${pretty_name}" == "moon" ]]; then
    sed -i '/text =/c text = "#e0def4"' alacritty.toml
    sed -i '/cursor =/c cursor = "#e0def4"' alacritty.toml
  elif [[ "${pretty_name}" == "dawn" ]]; then
    sed -i '/text =/c text = "#575279"' alacritty.toml
    sed -i '/cursor =/c cursor = "#797593"' alacritty.toml
  fi

  cd "${XDG_CONFIG_HOME}"/bat || exit
  if [[ "${mode}" == 'dark' ]]; then
    echo '--theme="OneHalfDark"' >config
  elif [[ "${mode}" == 'light' ]]; then
    echo '--theme="OneHalfLight"' >config
  fi

  cd "${XDG_CONFIG_HOME}"/btop || exit
  ln -sf "rose-pine/rose-pine${name}.theme" themes/theme.theme

  cd "${XDG_CONFIG_HOME}"/dunst || exit
  ln -sf "../themes/rose-pine/rose-pine${name}.conf" dunstrc.d/01-theme.conf

  cd "${XDG_CONFIG_HOME}"/hypr/hyprland || exit
  ln -sf "rose-pine/rose-pine${name}.conf" themes/colors
  if ! hyprctl reload >/dev/null 2>&1; then
    printf 'Failed to update for Hyprland.\nInstance Signature out-of-date?\n' >&2
    exit 1
  fi

  cd "${XDG_CONFIG_HOME}"/rofi || exit
  ln -sf "rose-pine/rose-pine${name}.rasi" themes/theme.rasi

  cd "${XDG_CONFIG_HOME}"/tmux || exit
  sed -i "s/rose_pine_variant '.*'/rose_pine_variant '${pretty_name}'/" tmux.conf
  tmux source-file tmux.conf

  cd "${XDG_CONFIG_HOME}"/waybar || exit
  ln -sf themes/rose-pine/"rose-pine${name}.css" colors.css
  killall -SIGUSR2 waybar

  exit
}

case "$1" in
light | dawn)
  name='-dawn'
  pretty_name='dawn'
  mode='light'
  change_theme
  ;;
dark | main)
  name=''
  pretty_name='main'
  mode='dark'
  change_theme
  ;;
moon)
  name='-moon'
  pretty_name='moon'
  mode='dark'
  change_theme
  ;;
*)
  printf 'usage: change-theme [light/dawn|dark/main|moon]\n' >&2
  exit 1
  ;;
esac
