#!/bin/bash
#
# Automatically disable some Hyprland decoration and theming options
# to increase performance.

if [[ $1 == 'on' ]]; then
  hyprctl --batch "\
        keyword animations:enabled 0;\
        keyword decoration:drop_shadow 0;\
        keyword decoration:blur:enabled 0;\
        keyword general:gaps_in 0;\
        keyword general:gaps_out 0;\
        keyword general:border_size 0;\
        keyword decoration:rounding 0"
  exit
fi
hyprctl reload
