#!/bin/bash
# shellcheck disable=1111
#
# Launch Gamescope with predefined options and (depending on mode)
# provided command.

mode=$1
declare -a flags
declare -a embedded_flags
declare -a nested_flags
# I would love to have unlimited refresh rate but games will not be able to
# detect something other than 60 Hz otherwise.
flags=(
  # Implies 2560*1440 (16:9).
  --output-height 1440
  --nested-refresh 144
)
embedded_flags=(--immediate-flips --adaptive-sync --prefer-output 'DP-1')
nested_flags=(--nested-unfocused-refresh 30 --fullscreen --force-grab-cursor --display-index 'DP-1')

help() {
  cat <<'EOT' >&2
gamescope-launch

Launch Gamescope with predefined options and/or provided command.

usage:
  gamescope-launch STEAM_MODE
	gamescope-launch MODE COMMAND

STEAM_MODE:
  steam-embedded
	steam-nested

MODE:
  embedded
	nested
EOT
}

case "${mode}" in
steam-embedded)
  if [ -n "$DISPLAY" ]; then
    cat <<-EOT >&2
			FATAL: Graphical session detected!
			Probably you meant to use “steam-nested”?
			EOT
    exit 2
  fi

  flags+=("${embedded_flags[@]}")
  flags+=(--steam)
  shift
  exec /usr/bin/gamemoderun /usr/bin/gamescope "${flags[@]}" -- steam -tenfoot -steamos
  ;;
steam-nested)
  flags+=("${nested_flags[@]}")
  flags+=(--steam)
  shift
  exec /usr/bin/gamemoderun /usr/bin/gamescope "${flags[@]}" -- steam
  ;;
embedded)
  if [ -n "$DISPLAY" ]; then
    cat <<-EOT >&2
			FATAL: Graphical session detected!
			Probably you meant to use “nested”?
			EOT
    exit 2
  fi

  flags+=("${embedded_flags[@]}")
  ;;
nested)
  flags+=("${nested_flags[@]}")
  ;;
*)
  help
  exit 1
  ;;
esac

shift
exec /usr/bin/gamemoderun /usr/bin/gamescope "${flags[@]}" -- "$@"
