#!/bin/bash
#
# Automatically kill select apps, services, and optionally relaunch them.

apps=(
  'udiskie'
)

apps_norestart=(
  'keepassxc'
  'protonmail-bridge'
)

user_services=(
  'mpd'
  'syncthing'
)

apps_norestart+=("${apps[@]}")

if [[ $1 == 'stop' ]]; then
  service_verb='stop'

  for app in "${apps_norestart[@]}"; do
    killall -q "${app}"
  done
else
  service_verb='start'
help() {
  printf 'usage: gamemode-autokill start/stop\n' >&2
}

if [[ $1 == 'stop' ]]; then
  killall -q "${apps_norestart[@]}"
elif [[ $1 == 'start' ]]; then
  for app in "${apps[@]}"; do
    /usr/bin/"${app}" &
  done
else
  help
  exit 1
fi

for service in "${user_services[@]}"; do
  systemctl --user "${service_verb}" -q --no-ask-password "${service}.service"
done
